name: Android-apk-build

on:
  workflow_dispatch:

jobs:
  build-android:
    name: 🎉 Android Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64

    - name: Install dependencies
      run: flutter pub get

    # Build the release APK
    - name: Build APK
      run: flutter build apk --release

    # Optionally, if you are using app bundles (.aab)
    # - name: Build Android App Bundle (AAB)
    #   run: flutter build appbundle --release

    - name: Upload APK to GitHub Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/app/outputs/flutter-apk/app-release.apk
        tag: v1.0
        overwrite: true
        body: "This is the first Android APK release"
